### ISSUE TITLE
Can't click manual seed selection

### ISSUE THREAD

**Issue by jtalley24** [JinghaoLu/MIN1PIPE#4]
Hi, 
I am trying to use manual seed selection. Everything looks good, and after figure 1 pop up, I thought every click has to make red dot, but click doesn't do anything. I tried drag, right click, middle click. How can I fix this issue?

**Comment by JinghaoLu** [comment]
Hi,
The correct codes have been uploaded. Thanks for pointing out the problem.
J

**Comment by jtalley24** [comment]
Thanks for the fixing!! I just tried once, it caused error. 

Error using lars_regression_noise (line 217)
An UndefinedFunction error was thrown on the workers for 'cvx_begin'.  This might be because the file containing 'cvx_begin' is not accessible on the workers.
Use addAttachedFiles(pool, files) to specify the required files to be attached.  See the documentation for 'parallel.Pool/addAttachedFiles' for more details.

Error in refine_roi (line 68)
            parfor i = 1: length(idt)  % estimate spatial components

Error in min1pipe (line 128)
            [roirf, bgr, sigupdt, seedsupdt, datasmthf1, cutofff1, pkcutofff1] = refine_roi(m, sig, bgf, roi, seeds, noise, datasmth0, cutoff0, pkcutoff0,
            ispara);

Error in demo_min1pipe (line 14)
[fname, frawname, fregname] = min1pipe(Fsi, Fsi_new, spatialr, se, ismc, flag);

Caused by:
    Undefined function 'cvx_begin' for input arguments of type 'char'.

I will look for why this error comes up, but if you have better answer, please tell me (crying)

**Comment by jtalley24** [comment]
@JinghaoLu That's a great help! Thanks! I worked really well!

**Comment by lumin223** [comment]
@JinghaoLu Hey, Thanks for sharing this awesome code. I am gladly using this. I am just reporting an issue. It's not a major flaw. After running multiple video analysis (for example, msCam1.avi, msCam2.avi... msCamX.avi), result files were generated in name of 'msCam_data_processed.mat, msCam_frame_all..). And at the last step (real neuron selection), the code only look for 'msCam1_data_processed' which is not generated by multiple video analysis. It makes all the analysis re-do because the code couldn't find 'msCam1_data_processed.mat' file. (msCam_data_processed were generated.) But it's not the major issue because there is already processed the file, so I can open manually.

**Comment by JinghaoLu** [comment]
@lumin223 Hi thanks for your interest in the code. As for the usage of "real_neuron_select", actually it does not automatically search for any .mat file. If you run it through the demo_min1pipe, a window pops up asking the user to select the file they want to inspect. From here you can choose the file "msCam_data_processed.mat". Is it possible that you point out the line and the file that contains this issue? Thanks for your effort. J

**Comment by JinghaoLu** [comment]
@jtalley24 The traces you click on are the bad ones, or false positive you think. For reference, jump to Usage -> Manual Options -> real_neuron_select. The third bullet point is about this.

**Comment by jtalley24** [comment]
@JinghaoLu omg;; thanks a lot! I shouldve look more carefully
