### ISSUE TITLE
Only 2500 frames processed

### ISSUE THREAD

**Issue by Mtkostecki** [JinghaoLu/MIN1PIPE#51]
Hi,

I have met another problem - my data is divided in 8 TIF files, 5000 frames each. The problem is that the program analyses only 2500 frames and only of the first file and is not processing the rest. Files are named MsCam1, MsCam2 etc, I would be grateful for a solution!

**Comment by JinghaoLu** [comment]
Hi, the algorithm identifies tif versus avi files in different ways, because these two are different by their main producers, inscopix versus ucla scope. If you are using separate tif files, the naming should be NAME.tif, NAME-1.tif, ..., NAME-n.tif. note the first file should only contains non-indexing characters that the other files use. In your case, the files should be named MsCam, MsCam1 etc. If avi files are used, they should be named in the way you mentioned.
